AWSTemplateFormatVersion: '2010-09-09'
Description: Storage S3 Bucket for TAME
Parameters:
  bucketName:
    Description: Name of S3 bucket
    Type: String
    Default: tame-storage-dev
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref bucketName
      Tags:
        - Key: project
          Value: tame
        - Key: env
          Value: dev
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - POST
            AllowedOrigins:
              - "*"
            ExposedHeaders:
              - x-amz-server-side-encryption
              - x-amz-request-id
              - x-amz-id-2
              - ETag
            MaxAge: "3000"
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Id: TameStorageBucketPolicy
        Version: '2012-10-17'
        Statement:
          - Sid: AllowWantedIps
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join ['', ['arn:aws:s3:::', !Ref S3Bucket, '/*']]
Outputs:
  BucketUrl:
    Value: !Join ['', ['https://', !GetAtt [S3Bucket, DomainName]]]
    Description: URL for S3 bucket
