AWSTemplateFormatVersion: '2010-09-09'
Description: Resource stack for deploying lambda code
Parameters:
  bucketName:
    Type: String
    Default: tame-lambda
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref bucketName
      Tags:
        - Key: project
          Value: tame
        - Key: env
          Value: dev
Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: Name of the S3 bucket
