AWSTemplateFormatVersion: '2010-09-09'
Description: Storage (S3) resource stack for TAME
Parameters:
  bucketName:
    Type: String
    Default: tame-dev-storage
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref bucketName
Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: Name of the S3 bucket
