AWSTemplateFormatVersion: '2010-09-09'
Description: Storage S3 Bucket for TAME
Parameters:
  BucketName:
    Description: Name of S3 bucket
    Type: String
    Default: tame-website-dev
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      Tags:
        - Key: project
          Value: tame
        - Key: env
          Value: dev
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Id: TameWebsiteBucketPolicy
        Version: '2012-10-17'
        Statement:
          - Sid: AllowWantedIps
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join ['', ['arn:aws:s3:::', !Ref S3Bucket, '/*']]
Outputs:
  WebsiteURL:
    Value: !GetAtt [S3Bucket, WebsiteURL]
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join ['', ['https://', !GetAtt [S3Bucket, DomainName]]]
    Description: Secure URL for S3 bucket
