AWSTemplateFormatVersion: '2010-09-09'
Description: Resource stack for deploying lambda code and CF templates
Parameters:
  bucketName:
    Type: String
    Default: conte-tame-deployment-dev
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref bucketName
Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: Name of the S3 bucket
